version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: geocoder
    versions:
    - 1.6.4
    - 1.6.5
    - 1.6.6
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
  - dependency-name: ffi
    versions:
    - 1.14.2
