---
:queues:
  - default
  - mailers
:schedule:
  GetTopStories:
    cron: '0 * * * *'
    class: GetTopStoriesJob
    queue: default
    description: 'Get the latest top stories'
  SendDailyStoryEmail:
    cron: '0 9 * * *'
    class: News::SendDailySummaryJob
    queue: default
    description: 'Send an email each day with the newest top stories'

